#!/bin/bash
set -e

echo "Building standalone dclaude script..."

# Check required files exist
for file in dclaude.sh Dockerfile docker-entrypoint.sh; do
    if [ ! -f "$file" ]; then
        echo "Error: $file not found"
        exit 1
    fi
done

# Create dist directory and output file
mkdir -p dist
OUTPUT="dist/dclaude-standalone.sh"

# Start with base script
cp dclaude.sh "$OUTPUT"

# Create awk script to inject content at placeholders
awk '
/INJECT:Dockerfile-start/ {
    print
    print "    # Embedded Dockerfile (generated by build.sh)"
    print "    DOCKERFILE_PATH=\"$SCRIPT_DIR/.dclaude-Dockerfile.tmp\""
    print "    cat > \"$DOCKERFILE_PATH\" <<'\''DOCKERFILE_EOF'\''"
    while ((getline line < "Dockerfile") > 0) {
        print line
    }
    close("Dockerfile")
    print "DOCKERFILE_EOF"
    print ""
    print "    # Embedded entrypoint script (generated by build.sh)"
    print "    # Note: Must write to docker-entrypoint.sh for Dockerfile COPY to work"
    print "    ENTRYPOINT_PATH=\"$SCRIPT_DIR/docker-entrypoint.sh\""
    print "    cat > \"$ENTRYPOINT_PATH\" <<'\''ENTRYPOINT_EOF'\''"
    while ((getline line < "docker-entrypoint.sh") > 0) {
        print line
    }
    close("docker-entrypoint.sh")
    print "ENTRYPOINT_EOF"
    print "    chmod +x \"$ENTRYPOINT_PATH\""
    # Skip everything until end marker
    while (getline > 0 && !/INJECT:Dockerfile-end/) { }
    next
}
{ print }
' dclaude.sh > "$OUTPUT.tmp"

# Add cleanup for embedded files to cleanup function
sed '/^cleanup() {/a\
    # Clean up embedded files\
    [ -f "$SCRIPT_DIR/.dclaude-Dockerfile.tmp" ] && rm -f "$SCRIPT_DIR/.dclaude-Dockerfile.tmp"\
    [ -f "$SCRIPT_DIR/docker-entrypoint.sh" ] && rm -f "$SCRIPT_DIR/docker-entrypoint.sh"
' "$OUTPUT.tmp" > "$OUTPUT"

rm "$OUTPUT.tmp"
chmod +x "$OUTPUT"

echo "✓ Created $OUTPUT"
echo "  Size: $(du -h "$OUTPUT" | cut -f1)"
echo ""
echo "Usage: ./$OUTPUT [options]"
